// import './jsxstudy/jsx-study1'
// import './jsxstudy/jsx-study2'
// import './component-basic/first-component'
// import './component-basic/animal-container'
// import './component-basic/props-basic'
// import './component-basic/props-children'
// import './component-basic/state-study-1'
// import './component-basic/state-study-3'
// import './component-intermediate/counter-demo'
import './component-intermediate/manipulate-list'